### PR TITLE
GitHub Actions

### PR DESCRIPTION
**Pull request by diegoferigo**
This PR adds the support of two workflows implemented with GitHub Actions #47:

- Build the CI docker image with a cron job
- Build and test the C++ project and the Python package

In the future we should also add another job that executes the tests from the PyPi package (#46).

Note that I already added iDynTree even if it is not currently necessary. I have few staging PRs that will need it soon.

### CODE REVIEW

**Comment by diegoferigo** [comment]
Tests are currently failing with the error reported below. Checking the old Travis CI logs (that were failing since some while) this error has been introduced few weeks ago after some upstream changes, and is unrelated to this PR.

In my setup I compile all the ignition libraries from source and I'm not affected (all tests pass). CI, instead, installs all the projects from binaries except ign-gazebo, because we still temporarily use my fork. I suspect that there is a mismatch between the hg and packaged version, but I didn't investigate that much.

```
Error [parser.cc:458] Missing <sdf> element.
Error [parser.cc:401] parse as old deprecated model file failed.
Error [parser_urdf.cc:3171] Unable to call parseURDF on robot model
Error [parser.cc:458] Missing <sdf> element.
Error [parser.cc:401] parse as old deprecated model file failed.
[Err] [Server.cc:198] Error Code 3 Msg: Required attribute[type] in element[atmosphere] is not specified in SDF.
[Err] [Server.cc:198] Error Code 7 Msg: Error reading element <atmosphere>
[Err] [Server.cc:198] Error Code 7 Msg: Error reading element <world>
[Err] [Server.cc:198] Error Code 7 Msg: Error reading element <sdf>
```

**Comment by diegoferigo** [comment]
The world I was loading didn't specify the `atmosphere` tag. For some reason, after [osrf/sdformat#571](https://bitbucket.org/osrf/sdformat/pull-requests/571/element-dont-print-unset-attributes/diff) that element is no longer inserted by default. Adding the following in the world solved the problem:

```xml
<atmosphere type="adiabatic"/>
```

Reference: [SDFormat@world#atmosphere](http://sdformat.org/spec?ver=1.6&elem=world#world_atmosphere).

**Comment by traversaro** [comment]
> The world I was loading didn't specify the `atmosphere` tag. For some reason, after [osrf/sdformat#571](https://bitbucket.org/osrf/sdformat/pull-requests/571/element-dont-print-unset-attributes/diff) that element is no longer inserted by default. Adding the following in the world solved the problem:
> 
> ```
> <atmosphere type="adiabatic"/>
> ```
> 
> Reference: [SDFormat@world#atmosphere](http://sdformat.org/spec?ver=1.6&elem=world#world_atmosphere).

This seems quite a regression, I would open an issue in https://bitbucket.org/osrf/sdformat/issues .

**Comment by diegoferigo** [comment]
> This seems quite a regression, I would open an issue in https://bitbucket.org/osrf/sdformat/issues .

Sure, I agree.

Actually there is another related problem ([CI log](https://github.com/diegoferigo/gym-ignition/commit/ee109deffb8fd8e6675683551b5e0f358a41e8db/checks?check_suite_id=245981075#step:7:386)):

```
Error [parser_urdf.cc:3171] Unable to call parseURDF on robot model
Error [parser.cc:458] Missing <sdf> element.
Error [parser.cc:401] parse as old deprecated model file failed.
Error [parser_urdf.cc:3171] Unable to call parseURDF on robot model
Error [parser.cc:458] Missing <sdf> element.
Error [parser.cc:401] parse as old deprecated model file failed.
[Err] [Server.cc:198] Error Code 3 Msg: Required attribute[name] in element[model] is not specified in SDF.
[Err] [Server.cc:198] Error Code 7 Msg: Error reading element <model>
[Err] [Server.cc:198] Error Code 7 Msg: Error reading element <world>
[Err] [Server.cc:198] Error Code 7 Msg: Error reading element <sdf>
```

This time, since the logic about inserting the model SDF into the world is going to change (I have a staging branch with it) and fixing it now would be wasted effort, I would ignore this error and merge this PR. As soon that the new logic will be merged, everything should be fine again. The tests locally already pass.

**Comment by diegoferigo** [comment]
> This seems quite a regression, I would open an issue in https://bitbucket.org/osrf/sdformat/issues .

For the record, I found the PR [osrf/sdformat#576](https://bitbucket.org/osrf/sdformat/pull-requests/576/fix-tostring-on-required-attributes-and/diff) already open upstream.

**Pull request merged**
