### PR TITLE
Improve Gazebo robot performance

### PR DESCRIPTION
**Pull request by diegoferigo**
Profiling a test execution from Python with cProfiler, it turned out that one of the most expensive operation (which is called also many times) is the lock of the robot weak pointer.

This PR refactors the gazebo robot class in such a way that it will store the shared pointer obtained by locking the weak pointer rather than the weak pointer itself.

Depends on #104, I will rebase this PR after merging it.

### CODE REVIEW

**Comment by traversaro** [comment]
> This PR refactors the gazebo robot class in such a way that it will store the shared pointer obtained by locking the weak pointer rather than the weak pointer itself.

Are you sure that this is not creating a shared pointer loop?

**Comment by diegoferigo** [comment]
I think that in this specific case, we should not suffer of loops. I tested the improvement of this PR for a while and I never encountered problems.

The main reason for the existence of the weak pointer for the robot object is due to the fact that the model could be removed from the simulation while other units (e.g. the Python task) still has a shared pointer to the robot object. In this case, the robot object would be useless because it would operate on entities and components that are no longer in the ECM.

With the weak pointer, this case would result in a failed lock occurring with the first method call of the robot object associated to the deleted model. If users do not use too much their fantasy and avoid fiddling with implementation details, this should never happen (and, to me, it never happened). The existence of the Python robot object (wrapping the C++ shared pointed) that streamlines insertion / deletion should prevent faulty usage.

In light of this, for the time being, I prefer having better performance than monitoring a very edge case that, moreover, is caused by a stretch of the framework.

**Comment by traversaro** [comment]
> I think that in this specific case, we should not suffer of loops. I tested the improvement of this PR for a while and I never encountered problems.

Ok, then it is ok for me. For future reference, I did not check personally for the fact that loop should not arise.

**Comment by diegoferigo** [comment]
Waiting to merge #104 before rebasing and merging this PR.

**Pull request merged**
