### PR TITLE
ScenarI/O unit testing - first pytest files

### PR DESCRIPTION
**Pull request by diegoferigo**
This PR introduces the first tests of the ScenarI/O Python APIs. I disabled the previous gym-ignition tests since most of the scenario test will cover them.

Note that this is only a starting point. There are many APIs not yet covered. There will be more PRs that extend the new testing suite.

---

A comment on the new `utils.gazebo_fixture` method. In order to clean the resources allocated after using the `scenario::gazebo::GazeboSimulator` class, the `GazeboSimulator::close` method must be called. This happens in the `~GazeboSimulator`, therefore, if the object is destructed, everything is cleaned successfully.

I noticed that when as assertion fails in a pytest, the test suite keep going on without deleting the objects it used. This means that the python instance of the `GazeboSimulator` is not destroyed and the `close()` method is not called. This is a big problem, because the following tests will find a `ignition::gazebo::Server` object in memory, with all the open transport topics and they might fail.

In order to fix this problem, we need to be sure than also in the case a tests fails after a failed assertion, at least the `close` method is called. The `utils.gazebo_fixture` was introduced for this very specific reason. It will `yield` the simulator instance and after an assertion the test will give back the execution to the fixture that will close the simulator.

### CODE REVIEW

**Comment by diegoferigo** [comment]
We might finally have a green CI back! Ready to be reviewed @traversaro

**Comment by diegoferigo** [comment]
Note that I had to enable the docker images to compile ign-gazebo from sources. There are two missing pieces in upstream:

- [`RenderUtil.patch`](https://gist.github.com/diegoferigo/ef860a73e5fc58d6236369ed684bf52e#file-renderutil-patch) This is required to update the GUI when the simulator is paused. It was discussed [here](https://bitbucket.org/ignitionrobotics/ign-gazebo/pull-requests/556/update-physics-state-even-when-paused-not/diff#comment-140108266), it has been already merged but it's not yet part of the branch we need.
- [`SimulatorRunner.patch`](https://gist.github.com/diegoferigo/ef860a73e5fc58d6236369ed684bf52e#file-simulationrunner-patch) It is a crucial feature for us, and it enables many of the features we need for the new bindings. It was discussed [here](https://bitbucket.org/ignitionrobotics/ign-gazebo/issues/51/allow-stepping-the-simulator-in-paused) but there's no open PR in upstream. I'm waiting that the migration to github will settle down to proceed. In the meantime, we have to manually apply this small patch.

**Comment by diegoferigo** [comment]
New versions of `FindPython` have greatly improved and they gained virtualenv awareness. Since we recommend using a virtualenv, I added a vendored version with a679e10bfa9041f8585869e26218537f2b5b9ca4.

For the records, given a virtualenv in `/rl/ve`, this is the output with the virtualenv enabled:

```
-- Python3_VERSION=3.6.9
-- Python3_STDLIB=/usr/lib/python3.6
-- Python3_STDARCH=/usr/lib/python3.6
-- Python3_SITELIB=/rl/ve/lib/python3.6/site-packages
-- Python3_SITEARCH=/rl/ve/lib/python3.6/site-packages
-- Python3_STDARCH=/usr/lib/python3.6
-- Python3_STDARCH=/usr/lib/python3.6
-- Python3_STDARCH=/usr/lib/python3.6
```

And this is without any virtualenv:

```
-- Python3_VERSION=3.6.9
-- Python3_STDLIB=/usr/lib/python3.6
-- Python3_STDARCH=/usr/lib/python3.6
-- Python3_SITELIB=/usr/lib/python3/dist-packages
-- Python3_SITEARCH=/usr/lib/python3/dist-packages
-- Python3_STDARCH=/usr/lib/python3.6
-- Python3_STDARCH=/usr/lib/python3.6
-- Python3_STDARCH=/usr/lib/python3.6
```

**Comment by traversaro** [comment]
Why SWIG  from sources?

**Comment by diegoferigo** [comment]
> Why SWIG from sources?

For the upcoming documentation we need features of v4 (doxygen integration).

**Comment by diegoferigo** [comment]
@traversaro I finally manage to fix also the User installation :tada: The new `FindPython` is a big step forward (apart from [this](https://gitlab.kitware.com/cmake/cmake/-/issues/20560)) :smile: I faced few problems in how the virtualenv was detected with the vendored modules, now it seems reliable.

Compiling the Physics system with gcc 7 and gcc 8 is extremely slow (also in my local machine), we might think to enable ccache in the CI pipeline. Locally I managed to run the tests also with gcc9 and clang9, we can also enable them again in the future.

CI is back :muscle:

**Pull request merged**
