### PR TITLE
Website scaffold

### PR DESCRIPTION
**Pull request by diegoferigo**
This PR initializes the empty website https://robotology.github.io/gym-ignition. It uses:

- [Sphinx](https://www.sphinx-doc.org/en/master/) as main platform.
- [Sphinx MultiVersion](https://holzhaus.github.io/sphinx-multiversion/) to handle multiple versions. Only `master`, `devel`, and `v*` tags are matched.

There are two new targets:

-  `doxygen` build the Doxygen documentation
- `sphinx` builds the website and generates the folder `<build>/html` that can be deployed

The integration between sphinx and doxygen is not yet there and it will be done in another PR. I managed to make Sphinx display also the C++ documentation using breathe, inspired by [this amazing tutorial](https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/), but I will populate APIs content in another PR.

At the moment I pushed the content manually. Sooner or later I will implement a new Workflow to automatize the process. 

---

Note: there is a similar [contrib extension](https://github.com/sphinx-contrib/sphinxcontrib-versioning) to build a multi-version website, but it's currently bugged (https://github.com/sphinx-contrib/sphinxcontrib-versioning/pull/78). Though, the SMV extension works quite well.

### CODE REVIEW

**Comment by traversaro** [comment]
I am not fully convinced by the `Gym-Ignition` name with both capital letters and dash `-`, but that is just personal taste.

**Comment by diegoferigo** [comment]
It is the name we used in our publication. Though, for the website we can change it and make it nicer. The two options are:

- Gym Ignition
- gym-ignition

**Comment by traversaro** [comment]
I personally like  `gym-ignition` because it is consistent with GitHub repo, pip package, package in any possible package manager in the world, but that is personal taste.

**Comment by diegoferigo** [comment]
And probably that would also work better for the indexing of search engines. Agreed.

**Pull request merged**
