### PR TITLE
Implement VELOCITY_DIRECT control mode

### PR DESCRIPTION
**Pull request by diegoferigo**
This control mode is DART-only but for the moment it is useful supporting it officially. It allows controlling models in simulation without the need to tune any PID. Joints controlled in `VELOCITY_DIRECT` follow velocity trajectories precisely. The physics engine is responsible to compute the right force to apply in order to follow the velocity references.

Note that this is not a realistic control mode. However, in many cases, it can provide a quick way to control models before starting the effort of tuning PID gains.

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Ok for me, but Velocity Direct seems to be  misleading name, especially for people working on YARP robots in which Position Direct has a completely different meaning. What about VELOCITY_NON_REALISTIC or VELOCITY_SIMULATION_ONLY ?

**Comment by diegoferigo** [comment]
This is not only simulation-specific, it is DART specific. If we want to make it more clear, I'd prefer going with something like `VelocityFollowerDart`. Other suggestions?

**Comment by traversaro** [comment]
> This is not only simulation-specific, it is DART specific. 

Ok for me to name it DART-specific, even if in theory other simulators could implement it as well.

**Comment by diegoferigo** [comment]
> Ok for me to name it DART-specific, even if in theory other simulators could implement it as well.

Since at the moment there aren't, I would go with this DART-only. We can add a new mode and deprecate this one in case other physics plugins would support something similar.

**Comment by traversaro** [comment]
Perfect!

**Comment by diegoferigo** [comment]
Name changed and documentation added in 5fc598e.

**Pull request merged**
