### PR TITLE
Implement JointType for Gazebo robots

### PR DESCRIPTION
**Pull request by diegoferigo**

### CODE REVIEW

**Comment by diegoferigo** [comment]
cc @raffaello-camoriano

**Comment by diegoferigo** [comment]
Just fixed a codacy complaint. [Here the diff](https://github.com/robotology/gym-ignition/compare/583cb143fa6eec63c264d2c0b0b354cb52ff2b2d..5ee8e5b066967ae873bf758baaba0539344b612e).

**Comment by diegoferigo** [comment]
> General comment: all these methods that take the jointName as input may be a bottleneck if used in a inner loop (but clearly this needs to be verified).

We need to profile the code once we have a complex enough application, I agree. Though, I think that the main bottleneck will not be a consequence of this choice. In general terms, since these methods are the only public APIs directly used by downstream users, I would rather prefer having a small overhead caused by strings rather than a more convoluted conversion with indices that might affect both readability and debugging.

**Comment by traversaro** [comment]
> We need to profile the code once we have a complex enough application, I agree. Though, I think that the main bottleneck will not be a consequence of this choice. In general terms, since these methods are the only public APIs directly used by downstream users, I would rather prefer having a small overhead caused by strings rather than a more convoluted conversion with indices that might affect both readability and debugging.

Just to clarify: using indices for APIs  is not the only option to mitigate this, other alternatives may be to return a structure with all the joint properties, to have only a single search in the hash, however as discussed changing this can be decided after profiling.

**Comment by diegoferigo** [comment]
Thanks for the clarification. I did not get you were referring to vectorized methods. I totally agree that we have to implement them, I opened https://github.com/robotology/gym-ignition/issues/126 to keep track of it.

**Pull request merged**
