### PR TITLE
Allow selecting whether to use system dependencies or download vendored

### PR DESCRIPTION
**Pull request by diegoferigo**
Fix https://github.com/robotology/gym-ignition/issues/256. 

Latest CMake refactoring done in https://github.com/robotology/gym-ignition/pull/233.

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by diegoferigo** [comment]
I got the following error when packaging the wheel (and not when builiding the plain CMake project):

>   CMake Error: install(EXPORT "ScenarioGazeboExport" ...) includes target "GazeboSimulator" which requires target "tiny-process-library" that is not in any export set.
  CMake Error in cpp/scenario/gazebo/CMakeLists.txt:
    export called with target "GazeboSimulator" which requires target
    "tiny-process-library" that is not in any export set.

Error in CI [here](https://github.com/robotology/gym-ignition/pull/275/checks?check_run_id=1412320124#step:16:363).

Last time I had to resort to a workaround that I tried to remove in a27723e. Apparently is still required. Trying another alternative in 9da3a7a from https://gitlab.kitware.com/cmake/cmake/-/issues/15415#note_634114.

cc @traversaro

**Comment by traversaro** [comment]
Another related issue may be https://gitlab.kitware.com/cmake/cmake/-/issues/18935 . In general OBJECT libraries and installations are definitely an area of CMake that is not really robust at the moment.

**Comment by diegoferigo** [comment]
>Another related issue may be https://gitlab.kitware.com/cmake/cmake/-/issues/18935 . In general OBJECT libraries and installations are definitely an area of CMake that is not really robust at the moment.

Yep, the fix didn't solve it:

>   CMake Error in cpp/scenario/gazebo/CMakeLists.txt:
    export called with target "GazeboSimulator" which requires target
    "tiny-process-library" that is not in any export set.

**Comment by diegoferigo** [comment]
I tried with STATIC library but when packaging the .a of TPL is installed in the wheel, and I don't like that. I reverted to OBJECT. In this case, a new exported target `ScenarioGazebo::tiny-process-library` is created but it looks harmless.

Let's wait CI and merge if this is ok.

**Pull request merged**
