### PR TITLE
Update to Ignition Dome

### PR DESCRIPTION
**Pull request by diegoferigo**
This PR updates our CI and CD pipelines to Ignition Dome. As stated in our support policy, we officially support the latest Ignition release, that now is Dome. However, while the binaries we distribute through PyPI will be compatible only with the officially release, I want to be more flexible about source installation. If there's no major API breaking, also previous releases could be unofficially used, especially in this case that Citadel is an LTS release.

I updated our CMake project for being compatible with multiple Ignition distributions. Unfortunately, the way the libraries are packaged and distributed in this case created quite a lot of challenges.

This PR contains new CMake macros:

- `FindIgnitionDistribution.cmake`: Looks for Ignition packages and tries to locate all the required one. For the time being, I only search for `ignition-gazeboX`.
- `AliasImportedTarget.cmake`: In the most generic case, allows to find a package e.g. `package3-all` with targets `packagenamespace3::target1` and creates alias variables: 1) `package-all` for the package, and 2) `packagenamespace.target` for the target.
- `ImportTargets{Citadel,Dome}`: Aliases all the Ignition targets required by the project so that out targets can link against them using CMake variables e.g. `${ignition-gazebo.core}`.

Furthermore, I refreshed the CI pipeline to not run in our Docker images. I realized that pulling the images from dockerhub was quite slow and building everything directly in the workflow could not be that much slower if combined with ccache. This new approach greatly simplifies maintaining the CI pipeline and also allows to add new configurations, which can be useful in the period close to new Ignition releases.

While we're not using them anymore for CI, the docker images are still used for CD, Website, and Demo. I updated them to Dome.

---

Notes: the Ignition ppa also has a nightly channel that could substitute building out nightly channel with colcon. However, I still prefer to build from sources in the case we want to temporarily use out forks with new features before they get accepted upstream.

### CODE REVIEW

**Comment by diegoferigo** [comment]
@traversaro ready for review

**Comment by traversaro** [comment]
> ImportTargets{Citadel,Dome}: Aliases all the Ignition targets required by the project so that out targets can link against them using CMake variables e.g. ${ignition-gazebo.core}.

I thought that the ignition libraries already provided some facilities to import not versioned imported targets, but probably I did not remember correctly. If all of this s necessary to support different ignition-gazebo versions, this is not a negligible boilerplate. I think the pattern followed by Qt for Qt5/Qt6 (https://www.qt.io/blog/versionless-cmake-targets-qt-5.15) ideally is the way to go.

**Comment by diegoferigo** [comment]
Thanks for providing the very solid use case of Qt, I was not aware of that. Basically the final result of this PR matches exactly that approach. I couldn't create any new CMake targets (e.g. by using ALIAS since it's not supported for imported targets) and I had to resort to CMake variables with names that mimic the unversioned original targets.

If there are official resources, I'm not aware of them. If you find anything, I'd be more than happy to update this PR. As you said, there's a lot of boilerplate code that took a while to implement, and I'm pretty sure is not even very robust.

Maybe @chapulina could chime in and shed some light?

**Comment by traversaro** [comment]
I guess https://github.com/ignitionrobotics/ign-cmake/issues/15 was a related discussion, but I am afraid there is no silver bullet at the moment for this use case. The huge number of transitive includes between ignition libraries would also complicate doing something like https://www.qt.io/blog/versionless-cmake-targets-qt-5.15 with its `QT_DEFAULT_MAJOR_VERSION` .

**Pull request merged**
