### PR TITLE
Add icub models

### PR DESCRIPTION
**Pull request by diegoferigo**
This PR adds the gazebo files for the following models:

- `iCubGazeboV2_5` from [`icub-modes`](https://github.com/robotology/icub-models)
- `iCubGazebo` from [`icub-gazebo`](https://github.com/robotology/icub-gazebo)

The ignition libraries can currently parse both files, but only the second is visualized (even if materials are not yet working):

icubgazebo

This repository contains vendored version of the `sdf` files, adapted to work in the new gazebo. The meshes instead are loaded from the original repositories, which must be cloned separately. As described in the README, environment variables must be properly configured.

### CODE REVIEW

**Comment by diegoferigo** [comment]
cc @traversaro

**Comment by traversaro** [comment]
The goal is to just keep this vendored version for quickly iterating with Ignition Gazebo support, and then port necessary improvements to `icub-models`?

**Comment by diegoferigo** [comment]
Yes, considering the early stage of this repository I'm trying to keep things simple. Ignition Gazebo works differently than Gazebo < 11, for instance you cannot load meshes using the `model://` scheme. At the current moment it is not possible to have a model that works on both versions.

In any case, this PR provides just an initial working configuration for these models. There are no Gym environments to use them yet. They will be useful to keep track the development of Ignition Libraries.

**Comment by traversaro** [comment]
Ack, I agree.

**Pull request merged**
