### PR TITLE
Align Physics system

### PR DESCRIPTION
**Pull request by diegoferigo**
Following the new procedure #315.

**Note: this PR breaks the compatibility with Ignition distributions older than Edifice**. Unfortunately, if we want to keep our current branching policy and keep the Physics system aligned with upstream, we cannot guarantee  (as documented) backward compatibility with previous distributions.

### CODE REVIEW

**Comment by diegoferigo** [comment]
It seems that there are few PRs targeting the Physics system that will be merged upstream in the next few days. I'll leave this PR open for few more days, maybe I can include them here as well.

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
>

**Review by traversaro — APPROVED** [review]

**Comment by diegoferigo** [comment]
In this PR, I also enabled the support to the profiler that could be helpful to debug https://github.com/robotology/gym-ignition/issues/319. As soon as I start this task, I'll write a short tutorial in Discussions. In the meantime, let's refer to the [upstream's documentation](https://github.com/ignitionrobotics/ign-common/blob/ign-common3/tutorials/profiler.md).

**Comment by diegoferigo** [comment]
Reminder for my future self. In I disabled some lines introduced in https://github.com/ignitionrobotics/ign-gazebo/pull/678 that were causing paused step to behave weird. Probably there's something strange in the caching of the link poses. Commenting out [these lines](https://github.com/robotology/gym-ignition/blob/4cab097bba4f06dce6d3b60005142a4ea171f3ab/cpp/scenario/plugins/Physics/Physics.cc#L1926-L1934) and forcing the changed state in 4cab097 fixed the visualization. There's some upstream effort to run server and gui in the same process, as soon as they will implement it, network transport is no longer needed and these problems should not arise.

<details>
<summary>Video</summary>

This is a pure kinematic visualization where only paused steps are run. Without the mentioned fix, the visual of the feet do not work properly. 

https://user-images.githubusercontent.com/469199/116291008-6667a900-a794-11eb-8a5c-d5b40ce31b3d.mp4

</details>

Reminder: I have to squash and merge this time.

**Comment by diegoferigo** [comment]
More details about the broadcasting of the Pose components for paused steps implemented in https://github.com/robotology/gym-ignition/commit/4cab097bba4f06dce6d3b60005142a4ea171f3ab can be found in https://github.com/ignitionrobotics/ign-gazebo/pull/544.

**Pull request merged**
