### PR TITLE
Address sdformat11 deprecations

### PR DESCRIPTION
**Pull request by diegoferigo**
Updates the code to sdformat11, and particularly complies with https://github.com/osrf/sdformat/pull/444.

---

This PR depends on #307 for Edifice support, and #318 for disabling Dome in CI.

### CODE REVIEW

**Review by traversaro — APPROVED** [review]
If I understand correctly, this changes the public ABI and API of the C++ Scenario package. If the project follows semantic versioning (see https://github.com/robotology/gym-ignition/issues/81#issue-508288841) this would mean that the major version needs to bump? If instead the compatibility policy is not  semantic versioning (even for a subset of the project) it would be convenient to document it in the README, for downstream packages.

**Comment by diegoferigo** [comment]
Uhm, the `helpers.h` is not a public header, but `utils.h` is public. So, yes, there's actually an API change:

```cpp
    // OLD
    std::string getModelNameFromSdf(const std::string& fileName,
                                    const size_t modelIndex = 0);
    // NEW
    std::string getModelNameFromSdf(const std::string& fileName);
``` 

I'm debating about how to handle the process. The PR targets Ignition Edifice which requires `sdformat11`, and `sdformat11` deprecated the functionality updated in this PR.

I think it's safe saying that we follow semantic versioning only for the ScenarIO interface. This is not part of it and I agree that we should document it somewhere.

**Comment by traversaro** [comment]
> I think it's safe saying that we follow semantic versioning only for the ScenarIO interface. This is not part of it and I agree that we should document it somewhere.

For convenient of downstream packages, it would be convenient to specify a API/ABI policy also for the part of ScenarIO that are not part of the interface, even just something as limited as API/ABI is not broken as part of the same patch release `x.y.z` .

**Comment by diegoferigo** [comment]
Yep, while you were commenting I opened https://github.com/robotology/gym-ignition/issues/337 as reminder.

**Pull request merged**
