### PR TITLE
Make Joint::jointGeneralizedForceTarget return data from the right component

### PR DESCRIPTION
**Pull request by diegoferigo**
Before #259, and particularly 5bf1b4b, we were handling differently what was stored in the `JointForce` component. Now, the force is filled by what the ign-physics plugin provides. Before, we were storing the command. In presence of friction or when the joint limit is reached, the command and the real joint force do not match.

This PR makes `gazebo::Joint::jointGeneralizedForceTarget` return the `JointForceCmd` instead. The trade off here is that this component is cleared after the first application, therefore getting the target is valid only before the next `GazeboSimulator::run()` call.

Until now, there have always been a mismatch about how the force target was handled wrt to the position, velocity, etc. This PR reduces the gap. It does not fill it entirely because the other targets will persist even after the run. However, this behaviour matches what happens in reality, since the force command is only applied once. Instead, when a joint controller is enabled, the position, velocity, etc. targets remain valid.

### CODE REVIEW

**Comment by diegoferigo** [comment]
Mmh I hoped that would have fixed CI, instead now I get the [following error](https://github.com/robotology/gym-ignition/pull/276/checks?check_run_id=1433367591#step:21:548):

```
/usr/bin/python3: symbol lookup error: /usr/local/lib/python3.8/dist-packages/scenario/lib/scenario/plugins/../../libComputedTorqueFixedBase.so: undefined symbol: _ZN8iDynTree11ModelLoader24loadReducedModelFromFileENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIS6_SaIS6_EES6_
```

I managed to reproduce it localle, and the symbol is actually missing:

```
❯ nm -C -u /rl/local/lib/libComputedTorqueFixedBase.so | grep iDynTree
                 U iDynTree::ModelLoader::loadReducedModelFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
```

Very strange, iDynTree is imported from the wheel as static libraries, and privately linked to create `libComputedTorqueFixedBase.so`. All the other iDynTree symbols used in the same compile unit are correctly found. cc @traversaro

**Comment by traversaro** [comment]
Which C++ ABI is used in the manywheel2014 compiler? If it is using the pre-c++11/gcc5 std::string ABI for std string, this could explain why you don't find an symbol that uses std::string when compiled with a compiler that is using post-c++11/gcc5 std::string ABI .

**Comment by diegoferigo** [comment]
I reached a similar conclusion, I noticed that the problematic methods are all those that have `std::string` as argument.

**Comment by diegoferigo** [comment]
It seems we have to pass `_GLIBCXX_USE_CXX11_ABI=0` when compiling iDynTree.

**Pull request merged**
