### PR TITLE
[`devel`]→[`master`] Preparation of v1.3.0

### PR DESCRIPTION
**Pull request by diegoferigo**
Edit: see update on renaming in https://github.com/robotology/gym-ignition/pull/361#issuecomment-871716902.

---

While I'd like to bring Edifice support to the Stable channel, I'm still unsure how to deal the temporary `scenar-io` name in PyPI introduced in #346. The renaming is currently blocked and is tracked in #359.

What I propose is the following. Move forward with the existing status and document in the release notes:

- Downstream projects that need to depend on `scenar-io` that this is a temporary name and it will change in one of the next minor releases.
- Downstream projects should:
   1) Try to stay updated with our releases and update their projects accordingly.
   2) Continue to depend on `gym-ignition` as they are already (since `scenar-io` is new). Read next point for more details.
- Downstream projects that depend on `gym-ignition` are not affected by this change and should not perform any action. Also,  users should not notice any difference. In fact, the new `gym-ignition>=1.3.0` depends on `scenar-io` and this new package will be installed automatically. Furthermore, the future renaming of #359 should not affect these users since the renamed `scenario` package will replace `scenar-io` and will be installed similarly as `gym-ignition>=1.X.0` dependency.

What do you think @traversaro? 

There are few features I'd like to try finalizing before the release:

- [x] Move content from `setup.py` to `setup.cfg` #355 
- [x] ~Add support to bullet physics engine #340 (needs a ign-physics release)~
- [x] Align the physics system with upstream #365
- [x] Document that the downstream usage of `cmake-build-extension` to deal with #346

### CODE REVIEW

**Comment by traversaro** [comment]
> What do you think @traversaro?

I think there should not be any problem in general, I imagine that once scenario is released on PyPI, we can make a scenar-io a dummy package that depends on scenario, at least for the first release?

**Comment by diegoferigo** [comment]
> > What do you think @traversaro?
> 
> I think there should not be any problem in general, I imagine that once scenario is released on PyPI, we can make a scenar-io a dummy package that depends on scenario, at least for the first release?

Exactly, this is the idea. Thinking more on the usage, I think that depending on `gym-ignition` instead of `scenar-io` is not a real workaround. In fact:

- Users that just need ScenarIO from Python will always be able to `import scenario` either with the temporary `scenar-io` package and the new renamed `scenario` package. The new release and the future renaming will not affect these users in any case.
- Users that need the CMake project included in the ScenarIO package will be affected regardless (I just realized it), and depending on `gym-ignition` is not a workaround. In fact, using `cmake-build-extension`, the real name of the package has to be used in [`cmake_depends_on`](https://github.com/diegoferigo/cmake-build-extension/blob/6363e56151125deca8143d67207ca67c731b87a4/src/cmake_build_extension/cmake_extension.py#L22), and this is affected by renaming. There's no smooth solution for this use case. Luckily, AFAIK we don't have external users using this pattern. If there are, let's hope they follow at least occasionally upstream and read the release notes. They will get in any case a broken build with this new release if they have `cmake_depends_on=gym-ignition` (reminder to myself, I need to document it).

**Comment by diegoferigo** [comment]
It seems that the migration due to renaming of ScenarIO is less complex than what I originally thought. It requires some manual action, but it seems straightforward. In any case, I don't know any project beyond those within our organization that use the exported targets of the PyPI packages.

I report here below what I will include in the release notes about this migration.

---

This release includes #346 that changes how we distribute the project in PyPI. Starting with `v1.3.0`, the PyPI package `gym-ignition` will only provide the Python resources of the `gym_ignition` module. A new `scenar-io` PyPI package will provide the C++ resources. The import names didn't change (`import gym_ignition`, `import scenario`), and downstream should not be affected in most cases. 

The process of claiming the `scenario` PyPI name is ongoing (https://github.com/pypa/pypi-support/issues/1082), and future releases will rename the new `scenar-io` package to `scenario` as soon as the name is released to us.

**Warning:** if a downstream Python package was using the exported CMake targets of ScenarIO, some maintenance action is necessary. These projects have `gym_ignition` in the `[build-system]/requires` of their `pyproject.toml`. 

In order to update to this `v.1.3.0` release, they have to:

- **`pyproject.toml`**: replace `gym_ignition` with `scenar-io ~= 1.3.0`.

As soon as https://github.com/pypa/pypi-support/issues/1082 gets closed and a new release will be published, they have to replace in their `pyproject.toml` the `scenar-io ~= 1.3.0` entry with `scenar-io ~= 1.X.0`. Refer to future release notes for further details.

**Review by traversaro — APPROVED** [review]

**Comment by diegoferigo** [comment]
Since https://github.com/pypa/pypi-support/issues/1082 is being processed, I'll wait to get the `scenario` PyPI name before merging into `master`. It will avoid the last change described in https://github.com/robotology/gym-ignition/pull/361#issuecomment-871716902.

Sadly, it postpones even more the landing of Edifice to the stable channel, but for those that need it, the nightly channel is fully operational (I use it as my daily drive).

**Comment by diegoferigo** [comment]
Note: the CI check on the `pull_request` event is failing because the changes of #376 require an upstream release.

**Comment by diegoferigo** [comment]
Waiting only for the `ignition-fortress` metapackage to land in the stable ubuntu ppa. After this, the CI of the PR that builds and tests the project against a released version of Ignition Gazebo should turn green.

Still in the TODO list before merging:

- [ ] Update the supported distribution of the stable channel in the website

**Pull request merged**
